displayName=No Drink In Bank
author=Welkon1
description=Removes drink option from potions while bank is open
tags=bank,potion,qol
plugins=com.example.NoDrinkInBankPlugin
repository=https://github.com/Welkon1/No-Drink-In-Bank
commit=c6d20c1ffb8280aa962d34e20fefb349e6bc00cc
